---
development:
  cloud_name: coposition
  api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
  enhance_image_tag: true
  static_image_support: false
  custom_transforms: {
    avatar: {
      transformation: ['list-pin-'],
      format: 'png'
    }
  }

staging:
  cloud_name: coposition
  api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
  enhance_image_tag: true
  static_image_support: true
  custom_transforms: {
    avatar: {
      transformation: ['list-pin-'],
      format: 'png'
    }
  }

production:
  cloud_name: coposition
  api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
  enhance_image_tag: true
  static_image_support: true
  custom_transforms: {
    avatar: {
      transformation: ['list-pin-'],
      format: 'png'
    }
  }

test:
  cloud_name: coposition
  api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
  enhance_image_tag: true
  static_image_support: false
  custom_transforms: {
    avatar: {
      transformation: ['list-pin-'],
      format: 'png'
    }
  }
