# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5009b4a407c9350f1ce99efa44c8f53866e5e37f14540295260bed09363b464e5d570d74eaaafa99f78c9b438849902d5d32448267fb5698e49101c71c8e8791
  mobile_app_key: "this-is-a-mobile-app"
  coposition_api_key: "this-is-a-coposition-api-key"
  mobile_app_api_key: "this-is-a-mobile-app-api-key"

benchmark:
  secret_key_base: "f27183615374ab533edf81d8e8992c8e9d005d879713403ae6d2b097877b14aa927c1fb72c4f84eefb9e536d4d7a8aa42dcddf5dc6c2e452392e29ed0ebe08e0"
  mobile_app_key: <%= ENV["MOBILE_APP_KEY"] %>
  webhook_url: <%= ENV["SLACK_WEBHOOK_URL"] %>
  coposition_api_key: "this-is-a-coposition-api-key"
  mobile_app_api_key: "this-is-a-mobile-app"

test:
  secret_key_base: 2c895373f134e0f9c184b80c2e9a8e796bca2be9e9b0bd306b08d30adada497f328202760f0e3520387e525f2a76a596e033a92f8da73d45b6ea9ac6ec7bd136
  mobile_app_key: "this-is-a-mobile-app"
  coposition_api_key: "this-is-a-coposition-api-key"
  mobile_app_api_key: "this-is-a-mobile-app-api-key"

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mobile_app_key: <%= ENV["MOBILE_APP_KEY"] %>
  webhook_url: <%= ENV["SLACK_WEBHOOK_URL"] %>
  coposition_api_key: <%= ENV["COPOSITION_API_KEY"] %>
  mobile_app_api_key: <%= ENV["MOBILE_APP_API_KEY"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mobile_app_key: <%= ENV["MOBILE_APP_KEY"] %>
  webhook_url: <%= ENV["SLACK_WEBHOOK_URL"] %>
  coposition_api_key: <%= ENV["COPOSITION_API_KEY"] %>
  mobile_app_api_key: <%= ENV["MOBILE_APP_API_KEY"] %>
